# USAGE NOTES:
#
# 1. If you use start.sh, it will create a db at ~/.silauto/db
# Otherwise, you will need to modify the mount for `silauto-api`
#
# 2. If you have multiple GPUs, you should duplicate teh silauto-worker
# but modify the CUDA_DEVICE so that there is 1 worker per device.

services:
  silauto-worker-1:
    build: worker
    restart: unless-stopped
    environment:
      - SILAUTO_URL=http://silauto-api:8000
      - SILNLP_ROOT=${HOME}/silnlp
      - SILNLP_DATA=${HOME}/silnlp_data
      - USFM2PDF_PATH=${USFM2PDF_PATH}
      - USERNAME=${USER}
      - CUDA_DEVICE=0
    volumes:
      - ${SSH_CONTAINER_KEY}:/app/.ssh/id_ed25519:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - silauto-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  silauto-worker-2:
    build: worker
    restart: unless-stopped
    environment:
      - SILAUTO_URL=http://silauto-api:8000
      - SILNLP_ROOT=${HOME}/silnlp
      - SILNLP_DATA=${HOME}/silnlp_data
      - USFM2PDF_PATH=${HOME}/Programming/usfm2pdf
      - USERNAME=${USER}
      - CUDA_DEVICE=1
    volumes:
      - ${HOME}/.ssh/container_key:/app/.ssh/id_ed25519:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - silauto-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  silauto-api:
    build: 
      context: server
      args:
      - UID: ${UID}
      - GID: ${GID}
    restart: unless-stopped
    environment:
    - SILNLP_DATA=${SILNLP_DATA}
    - MAX_CONCURRENT_FILE_PROCESSING=10
    - DATABASE_PATH=/app/db
    - CLIENT_PATH=/app/client
    volumes:
    - ${SILNLP_DATA}:${SILNLP_DATA}
    - ${HOME}/.silauto/db:/app/db
    ports:
    - "8000:8000"
    networks:
      - silauto-net

networks:
  silauto-net:
    driver: bridge
